name: music_scanner
description: Flutter音乐扫描插件,通过媒体库查找手机上的音乐数据
version: 1.0.0
author: xiaohuihuiold <xiaohuihuiold@gmail.com>
homepage: https://github.com/xiaohuihuiold/music_scanner

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  json_serializable: ^3.2.2

flutter:
  plugin:
    androidPackage: com.xhhold.flutter.plugin.musicscanner
    pluginClass: MusicScannerPlugin

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
